version: "3.3"
services:
  gitcthulu:
    build:
      context: .
    container_name: gitcthulu
    ports:
     - "9001:9001"
    networks:
     - gitcthulu-network
    image: itassistors/gitcthulu
    working_dir: /go/src/github.com/neel1996/gitcthulu-server
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
    volumes: 
      - /:/opt
    entrypoint: /go/src/github.com/neel1996/gitcthulu-server/dist/gitcthulu-server
networks:
  gitcthulu-network:
    driver: bridge
