apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitcthulu
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitcthulu
  template:
    metadata:
      labels:
        app: gitcthulu
    spec:
      containers:
      - name: gitcthulu
        image: itassistors/gitcthulu
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9001
